services:
  - type: background
    name: dentist-bot
    env: python
    framework: ""
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python dentist_bot.py
    envVars:
      - key: STOMBOT_TOKEN
        value: {{ YOUR_TELEGRAM_BOT_TOKEN }}
